In [29]:
#1
import numpy as np
STUDENT_NAME = "Kaye Celene G. Rivera"
STUDENT_ID = 5870

np.random.seed(STUDENT_ID)
data = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
print(f"{STUDENT_NAME}'s Array:", data)

mean_val = np.mean(data)
std_val = np.std(data)
print("Mean:", mean_val, "Std Dev:", std_val)

Kaye Celene G. Rivera's Array: [103  96  51  18  43  46 116  29  16  68]
Mean: 58.6 Std Dev: 33.988821691844514


In [28]:
#2
import numpy as np
STUDENT_NAME = "Kaye Celene G. Rivera"
STUDENT_ID = 5870

np.random.seed(STUDENT_ID)
matrix = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
print(f"{STUDENT_NAME}'s Matrix:\n", matrix)

row_sums = np.sum(matrix, axis=1)
col_sums = np.sum(matrix, axis=0)
print("Row sums:", row_sums)
print("Column sums:", col_sums)

Kaye Celene G. Rivera's Matrix:
 [[39 32 18 29]
 [16  4 32 18]
 [25  2  4 37]]
Row sums: [118  70  68]
Column sums: [80 38 54 84]


In [30]:
#3
import numpy as np
STUDENT_NAME = "Kaye Celene G. Rivera"
STUDENT_ID = 5870   

np.random.seed(STUDENT_ID)
arr3d = np.random.randint(0, STUDENT_ID % 20 + 10, size=(3,3,3))
print(f"{STUDENT_NAME}'s 3D Array:\n", arr3d)

slice_mid = arr3d[:,1,:]
print("Slice[:,1,:]:\n", slice_mid)

Kaye Celene G. Rivera's 3D Array:
 [[[ 6 18 17]
  [10 13 19]
  [15  3 17]]

 [[ 1 10 18]
  [ 3 11  4]
  [ 1 16 12]]

 [[ 7 15  8]
  [15  9 19]
  [13  6  3]]]
Slice[:,1,:]:
 [[10 13 19]
 [ 3 11  4]
 [15  9 19]]


In [31]:
#4
import numpy as np
STUDENT_NAME = "Kaye Celene G. Rivera"
STUDENT_ID = 5870

np.random.seed(STUDENT_ID)
x = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
filtered = x[(x > STUDENT_ID % 50) & (x < STUDENT_ID % 100)]
print(f"{STUDENT_NAME}'s Original:", x)
print("Filtered subset:", filtered)

Kaye Celene G. Rivera's Original: [103  96  51  18  43  46 116  29  16  68]
Filtered subset: [51 43 46 29 68]


In [32]:
#5
import numpy as np
STUDENT_NAME = "Kaye Celene G. Rivera"
STUDENT_ID = 5870

np.random.seed(STUDENT_ID)
A = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
B = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
print("Matrix A:\n", A)
print("Matrix B:\n", B)

product = A @ B
det_A = np.linalg.det(A)
print("A @ B:\n", product)
print("Determinant of A:", det_A)

Matrix A:
 [[39 32]
 [18 29]]
Matrix B:
 [[16  4]
 [32 18]]
A @ B:
 [[1648  732]
 [1216  594]]
Determinant of A: 555.0


In [33]:
#6
import numpy as np
STUDENT_NAME = "Kaye Celene G. Rivera"
STUDENT_ID = 5870

angles = np.linspace(0, 2*np.pi, 8)
sine_vals = np.sin(angles)
cos_vals = np.cos(angles)
print(f"{STUDENT_NAME}'s Angles:", angles)
print("Sine:", sine_vals)
print("Cosine:", cos_vals)

Kaye Celene G. Rivera's Angles: [0.         0.8975979  1.7951958  2.6927937  3.5903916  4.48798951
 5.38558741 6.28318531]
Sine: [ 0.00000000e+00  7.81831482e-01  9.74927912e-01  4.33883739e-01
 -4.33883739e-01 -9.74927912e-01 -7.81831482e-01 -2.44929360e-16]
Cosine: [ 1.          0.6234898  -0.22252093 -0.90096887 -0.90096887 -0.22252093
  0.6234898   1.        ]


In [34]:
#7
import numpy as np
STUDENT_NAME = "Kaye Celene G. Rivera"
STUDENT_ID = 5870

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(4,4))
arr[::2, ::2] = 0
print(f"{STUDENT_NAME}'s Modified 4x4 Array:\n", arr)

Kaye Celene G. Rivera's Modified 4x4 Array:
 [[ 0 32  0 29]
 [16  4 32 18]
 [ 0  2  0 37]
 [27  2 27 30]]


In [10]:
#8
import numpy as np
STUDENT_NAME = "Kaye Celene G. Rivera"
STUDENT_ID = 5870

np.random.seed(STUDENT_ID)
scores = np.random.randint(0, STUDENT_ID % 100 + 50, 10)
grades = np.where(scores >= STUDENT_ID % 70, 'Pass', 'Fail')
print(f"{STUDENT_NAME}'s Scores:", scores)
print("Grades:", grades)

Kaye Celene G. Rivera's Scores: [102  95  50  17  42  45 115  28  15  67]
Grades: ['Pass' 'Pass' 'Fail' 'Fail' 'Fail' 'Fail' 'Pass' 'Fail' 'Fail' 'Pass']


In [35]:

#9
import numpy as np
STUDENT_NAME = "Kaye Celene G. Rivera"
STUDENT_ID = 5870

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
flat_arr = arr.flatten()
transposed_arr = arr.T
print("Original array:\n", arr)
print("Flattened:", flat_arr)
print("Transposed:\n", transposed_arr)

Original array:
 [[39 32 18 29]
 [16  4 32 18]
 [25  2  4 37]]
Flattened: [39 32 18 29 16  4 32 18 25  2  4 37]
Transposed:
 [[39 16 25]
 [32  4  2]
 [18 32  4]
 [29 18 37]]


In [12]:
#10
import numpy as np
STUDENT_NAME = "Kaye Celene G. Rivera"
STUDENT_ID = 5870

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, (3,3))
mask = arr % 2 == 0
arr[mask] = -1
print("Array with conditional replacements:\n", arr)

Array with conditional replacements:
 [[39 -1 -1]
 [29 -1 -1]
 [-1 -1 25]]


In [36]:
#11
import numpy as np
import pandas as pd
STUDENT_NAME = "Kaye Celene G. Rivera"
STUDENT_ID = 5870

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'Name': [STUDENT_NAME]*5,
 'Score': np.random.randint(STUDENT_ID%50, STUDENT_ID%100+50, 5),
 'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10, 5)
})
print(df)

                    Name  Score  YearsCodePro
0  Kaye Celene G. Rivera    115            19
1  Kaye Celene G. Rivera     70            15
2  Kaye Celene G. Rivera     37             3
3  Kaye Celene G. Rivera     62            17
4  Kaye Celene G. Rivera     65             1


In [37]:
#12
import numpy as np
import pandas as pd
STUDENT_NAME = "Kaye Celene G. Rivera"
STUDENT_ID = 5870

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'EdLevel': ['Bachelor', 'Master', 'PhD', 'Bachelor', 'Master'],
 'ConvertedComp': np.random.randint(40000, 150000, 5)
})
avg_salary = df.groupby('EdLevel')['ConvertedComp'].mean()
print(avg_salary)

EdLevel
Bachelor     99916.0
Master       75718.5
PhD         140191.0
Name: ConvertedComp, dtype: float64


In [38]:
#13
import numpy as np
import pandas as pd
STUDENT_NAME = "Kaye Celene G. Rivera"
STUDENT_ID = 5870

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'Country': ['Philippines', 'USA', 'UK', 'Canada', 'Germany'],
 'ConvertedComp': np.random.randint(40000, 150000, 5)
})

top5 = df.sort_values(by='ConvertedComp', ascending=False)
print(top5)

       Country  ConvertedComp
2           UK         140191
3       Canada         103154
0  Philippines          96678
1          USA          87612
4      Germany          63825


In [39]:
#14
import numpy as np
import pandas as pd
STUDENT_NAME = "Kaye Celene G. Rivera"
STUDENT_ID = 5870

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
 'Name': [STUDENT_NAME]*5,
 'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10, 5)
})
high_exp = df[df['YearsCodePro'] > STUDENT_ID%10]
print(high_exp)

                    Name  YearsCodePro
0  Kaye Celene G. Rivera             6
1  Kaye Celene G. Rivera            18
2  Kaye Celene G. Rivera            17
3  Kaye Celene G. Rivera            10
4  Kaye Celene G. Rivera            13


In [40]:
#15
import numpy as np
import pandas as pd
STUDENT_NAME = "Kaye Celene G. Rivera"
STUDENT_ID = 5870

np.random.seed(STUDENT_ID)

df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})

bins = [0, 50000, 100000, 150000, 200000]
labels = ['0-50k', '50-100k', '100-150k', '>150k']

df['Bracket'] = pd.cut(df['ConvertedComp'], bins=bins, labels=labels)
print(df)

   ConvertedComp   Bracket
0          96678   50-100k
1          87612   50-100k
2         140191  100-150k
3         103154  100-150k
4          63825   50-100k


In [41]:
#16
import numpy as np
import pandas as pd
STUDENT_NAME = "Kaye Celene G. Rivera"
STUDENT_ID = 5870

np.random.seed(STUDENT_ID)

# Original Code Issue:
# np.random.randint(STUDENT_ID%40000, STUDENT_ID%150000, 5)
# -> np.random.randint(12345, 12345, 5) which is a zero-length range.

df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})
df['LogComp'] = np.log(df['ConvertedComp'])
print(df)

   ConvertedComp    LogComp
0          96678  11.479141
1          87612  11.380673
2         140191  11.850761
3         103154  11.543978
4          63825  11.063900


In [42]:
#17
import numpy as np
import pandas as pd
STUDENT_NAME = "Kaye Celene G. Rivera"
STUDENT_ID = 5870

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
 'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10, 5),
 'ConvertedComp': np.random.randint(40000, 150000, 5) 
})

corr_matrix = df.corr()
print(corr_matrix)

               YearsCodePro  ConvertedComp
YearsCodePro       1.000000       0.255213
ConvertedComp      0.255213       1.000000


In [47]:
#18
import numpy as np
import pandas as pd
STUDENT_NAME = "Kaye Celene G. Rivera"
STUDENT_ID = 5870

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
 'EdLevel':['Bachelor','Master','PhD','Bachelor','Master'],
 'ConvertedComp': np.random.randint(40000, 150000, 5) 
})

# Calculate mean, median, and standard deviation for each 'EdLevel'
summary = df.groupby('EdLevel')['ConvertedComp'].agg(['mean','median','std']).reset_index()
print(summary)

    EdLevel      mean    median           std
0  Bachelor   99916.0   99916.0   4579.223515
1    Master   75718.5   75718.5  16819.949004
2       PhD  140191.0  140191.0           NaN


In [48]:
#19
import numpy as np
import pandas as pd
STUDENT_NAME = "Kaye Celene G. Rivera"
STUDENT_ID = 5870

np.random.seed(STUDENT_ID)

# Generate salaries: [100727, 136195, 130612, 100727, 95233]
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})

threshold = 110000

# Create the 'HighPay' column using np.where()
df['HighPay'] = np.where(df['ConvertedComp'] > threshold, 'Yes', 'No')
print(df)

   ConvertedComp HighPay
0          96678      No
1          87612      No
2         140191     Yes
3         103154      No
4          63825      No


In [49]:
#20
import numpy as np
import pandas as pd
STUDENT_NAME = "Kaye Celene G. Rivera"
STUDENT_ID = 5870

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
 'Country': ['Philippines','USA','UK','Canada','Germany'],
 'ConvertedComp': np.random.randint(40000, 150000, 5)
})

# Group by 'Country' and calculate the mean and max 'ConvertedComp'
top_countries = df.groupby('Country')['ConvertedComp'].agg(['mean','max'])
print(top_countries)

                 mean     max
Country                      
Canada       103154.0  103154
Germany       63825.0   63825
Philippines   96678.0   96678
UK           140191.0  140191
USA           87612.0   87612
