# Creating NumPy Arrays

In [31]:
# Step 1: Import NumPy
import numpy as np

# Step 2: Create a 1D array representing years of experience
years_exp = np.array([1, 3, 5, 7, 10])
print("Years of Experience:", years_exp)

# Step 3: Create a 2D array representing sample salaries (in thousands)
salaries = np.array([[50, 60, 70], [80, 90, 100]])
print("Salary Matrix:\n", salaries)

# Step 4: Create an array of zeros and ones for placeholder analysis
zeros_array = np.zeros((2, 2)) # 2x2 zeros
ones_array = np.ones((2, 3)) # 2x3 ones
print("Zeros Array:\n", zeros_array)
print("Ones Array:\n", ones_array)

Years of Experience: [ 1  3  5  7 10]
Salary Matrix:
 [[ 50  60  70]
 [ 80  90 100]]
Zeros Array:
 [[0. 0.]
 [0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [2]:
# --- Try It: Creating NumPy Arrays ---

# 1. Add 2 more sample data points to years_exp (1D array)
# We use np.append to add [12, 15] to the existing array
years_exp = np.append(years_exp, [12, 15])
print("Updated Years of Experience:", years_exp)

# 2. Add 2 more data points to salaries (2D array)
# Note: Since the original has 3 columns, our new data must also have 3 columns.
# axis=0 means we are adding a new row.
new_rows = np.array([[110, 120, 130], [140, 150, 160]])
salaries = np.append(salaries, new_rows, axis=0)

print("\nUpdated Salary Matrix:\n", salaries)

# 3. Create a 3x3 identity matrix
# The function np.eye(n) creates a square matrix with 1s on the diagonal.
identity_3x3 = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_3x3)

Updated Years of Experience: [ 1  3  5  7 10 12 15]

Updated Salary Matrix:
 [[ 50  60  70]
 [ 80  90 100]
 [110 120 130]
 [140 150 160]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Array Operations


In [32]:
# Step 1: Element-wise addition
exp_plus_5 = years_exp + 5 # Add 5 years to all experience values
print("Years + 5:", exp_plus_5)

# Step 2: Element-wise multiplication
exp_times_2 = years_exp * 2 # Multiply all values by 2
print("Years * 2:", exp_times_2)

# Step 3: Dot product (simulate salary projections)
sample1 = np.array([1, 2, 3])
sample2 = np.array([4, 5, 6])
dot_result = np.dot(sample1, sample2)
print("Dot Product:", dot_result)

Years + 5: [ 6  8 10 12 15]
Years * 2: [ 2  6 10 14 20]
Dot Product: 32


In [33]:
# --- Try It: Array Operations ---

# 1. Experiment with subtraction and division
# 2. Apply np.exp() (Exponential)
# This calculates e raised to the power of each element
# 3. Apply np.log() (Natural Logarithm)
# This calculates the natural log (ln) of each element

minus_ones = years_exp - 1
halved = years_exp / 2
log_vals = np.log(years_exp)

print("Minus 1:", minus_ones)
print("Halved:", halved)
print("Logarithm:", log_vals)

Minus 1: [0 2 4 6 9]
Halved: [0.5 1.5 2.5 3.5 5. ]
Logarithm: [0.         1.09861229 1.60943791 1.94591015 2.30258509]


# Indexing and Slicing

In [34]:
# Step 1: Access individual element
print("First year of experience:", years_exp[0])

# Step 2: Slice arrays
print("First two salaries:", salaries[0, :2]) # First two elements of first row

# Step 3: Access all rows for a specific column
print("Second column salaries:", salaries[:, 1])

# Step 4: Negative indexing
print("Last year of experience:", years_exp[-1])

First year of experience: 1
First two salaries: [50 60]
Second column salaries: [60 90]
Last year of experience: 10


In [8]:
# --- Try It: Slicing and Indexing ---

# 1. Reverse arrays using slicing
# The [::-1] tells Python: "Start at the end, end at the start, step back by 1"
reversed_years = years_exp[::-1]
print("Reversed Years of Experience:", reversed_years)

# 2. Slice 2D arrays for subgroups of salaries
# Let's extract a 2x2 "mini-grid" from the top-left of your salaries matrix
# salaries[rows, columns] -> [0:2 (rows 0 and 1), 0:2 (columns 0 and 1)]
salary_subgroup = salaries[0:2, 0:2]

print("\nOriginal Salary Matrix:\n", salaries)
print("\nSubgroup (Top-left 2x2):\n", salary_subgroup)

Reversed Years of Experience: [15 12 10  7  5  3  1]

Original Salary Matrix:
 [[ 50  60  70]
 [ 80  90 100]
 [110 120 130]
 [140 150 160]]

Subgroup (Top-left 2x2):
 [[50 60]
 [80 90]]


# Reshaping and Dimensions

In [9]:
# Step 1: Reshape 1D array into 2x3 matrix for batch analysis
reshaped_exp = np.reshape(np.arange(1, 7), (2, 3))
print("Reshaped Experience Array:\n", reshaped_exp)

# Step 2: Flatten 2D arrays back into 1D
flattened_exp = reshaped_exp.flatten()
print("Flattened Array:", flattened_exp)

# Step 3: Transpose example
print("Transposed Array:\n", reshaped_exp.T)

Reshaped Experience Array:
 [[1 2 3]
 [4 5 6]]
Flattened Array: [1 2 3 4 5 6]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]


In [11]:
# --- Try It: Reshaping and Dimensions ---

# 1. Create a larger 1D array to experiment with (12 elements)
# np.arange(12) gives numbers 0 through 11
data_12 = np.arange(12)
print("Original 1D Data:", data_12)

# 2. Reshape into different dimensions
# Note: The new dimensions MUST multiply to the total number of elements (12)

# Option A: Reshape into 3 rows and 4 columns (3x4)
reshaped_3x4 = data_12.reshape(3, 4)
print("\nReshaped to 3x4 Matrix:\n", reshaped_3x4)

# Option B: Reshape into 4 rows and 3 columns (4x3)
reshaped_4x3 = data_12.reshape(4, 3)
print("\nReshaped to 4x3 Matrix:\n", reshaped_4x3)

# Option C: 3D Array (2 blocks, 3 rows, 2 columns) - Used in image processing
reshaped_3D = data_12.reshape(2, 3, 2)
print("\nReshaped to 3D Array (2x3x2):\n", reshaped_3D)

# 3. Quick Experiment with Transpose (.T)
# This flips the rows and columns
print("\nTransposed 4x3 to 3x4:\n", reshaped_4x3.T)

Original 1D Data: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped to 3x4 Matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped to 4x3 Matrix:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Reshaped to 3D Array (2x3x2):
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

Transposed 4x3 to 3x4:
 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


# Broadcasting in NumPy

In [12]:
# Step 1: Add a bonus array to salaries using broadcasting
bonus = np.array([5, 10, 15])
salaries_with_bonus = salaries + bonus # Adds corresponding bonus to each column
print("Salaries after bonus:\n", salaries_with_bonus)

Salaries after bonus:
 [[ 55  70  85]
 [ 85 100 115]
 [115 130 145]
 [145 160 175]]


In [35]:
# --- Try It: Broadcasting ---

# 1. Multiply by a single scaling factor (Scalar Broadcasting)
# Let's say everyone gets a 10% raise (multiply by 1.1)
scaling_factor = 1.1
scaled_salaries = salaries * scaling_factor

print("Original Salaries:\n", salaries)
print("\nSalaries after 10% raise (Scalar Scaling):\n", scaled_salaries)

# 2. Multiply by a specific scaling factor per column
# Imagine different departments get different performance multipliers
# Column 1: x1.0, Column 2: x1.2, Column 3: x1.5
performance_multipliers = np.array([1.0, 1.2, 1.5])
weighted_salaries = salaries * performance_multipliers

print("\nSalaries after Performance Multipliers:\n", weighted_salaries)

Original Salaries:
 [[ 50  60  70]
 [ 80  90 100]]

Salaries after 10% raise (Scalar Scaling):
 [[ 55.  66.  77.]
 [ 88.  99. 110.]]

Salaries after Performance Multipliers:
 [[ 50.  72. 105.]
 [ 80. 108. 150.]]


# Statistical Operations


In [17]:
# Step 1: Mean of years of experience
print("Mean experience:", np.mean(years_exp))

# Step 2: Standard deviation of experience
print("Std deviation of experience:", np.std(years_exp))

# Step 3: Max and Min salaries
print("Max salary:", np.max(salaries), "Min salary:", np.min(salaries))

# Step 4: Sum of salaries
print("Sum of all salaries:", np.sum(salaries))

Mean experience: 7.571428571428571
Std deviation of experience: 4.655477353371521
Max salary: 160 Min salary: 50
Sum of all salaries: 1260


In [16]:
# --- Try It: Statistical Operations ---

# 1. Compute the Median
# Note: Unlike the Mean (average), the Median is not affected by outliers.
median_exp = np.median(years_exp)
print("Median experience:", median_exp)

# 2. Compute Percentiles
# Let's find the 25th (1st quartile) and 75th (3rd quartile) percentiles
p25 = np.percentile(years_exp, 25)
p75 = np.percentile(years_exp, 75)

print(f"25th Percentile: {p25}")
print(f"75th Percentile: {p75}")

# 3. Compute Median for 2D arrays (Salaries)
# You can do this for the whole matrix, or per column (axis=0)
median_salaries_per_col = np.median(salaries, axis=0)
print("\nMedian salary per column (department/role):", median_salaries_per_col)

Median experience: 7.0
25th Percentile: 4.0
75th Percentile: 11.0

Median salary per column (department/role): [ 95. 105. 115.]


# NumPy Functions on Arrays


In [18]:
# Step 1: Apply trigonometric functions
angles = np.array([0, np.pi/4, np.pi/2])
print("Sine of angles:", np.sin(angles))
print("Cosine of angles:", np.cos(angles))

# Step 2: Apply function along rows (sum salaries per person)
salary_sums = np.apply_along_axis(np.sum, 1, salaries)
print("Sum of Salaries per person:", salary_sums)

Sine of angles: [0.         0.70710678 1.        ]
Cosine of angles: [1.00000000e+00 7.07106781e-01 6.12323400e-17]
Sum of Salaries per person: [180 270 360 450]


In [19]:
# --- Try It: Math Transformations & Custom Functions ---

# 1. Use np.sqrt() and np.log() for transformations
# Square root is often used in signal processing (like finding RMS)
sqrt_years = np.sqrt(years_exp)
# Log transformation is great for "squashing" data that has huge outliers
log_salaries = np.log(salaries)

print("Square root of years:", sqrt_years)
print("\nLog-transformed salaries:\n", log_salaries)

# 2. Apply a CUSTOM function using np.apply_along_axis()
# Let's define a function that calculates a "Performance Score"
# (Average salary * 0.1 for simplicity)
def calculate_bonus_rate(row):
    return np.mean(row) * 0.1

# We apply it across axis 1 (rows)
bonus_rates = np.apply_along_axis(calculate_bonus_rate, 1, salaries)

print("\nCustom Bonus Rate per person (row):", bonus_rates)

Square root of years: [1.         1.73205081 2.23606798 2.64575131 3.16227766 3.46410162
 3.87298335]

Log-transformed salaries:
 [[3.91202301 4.09434456 4.24849524]
 [4.38202663 4.49980967 4.60517019]
 [4.70048037 4.78749174 4.86753445]
 [4.94164242 5.01063529 5.07517382]]

Custom Bonus Rate per person (row): [ 6.  9. 12. 15.]


# Integrating NumPy and Pandas for Analysis


In [20]:
import pandas as pd

# Step 1: Create a NumPy array of random data
data = np.random.randint(1, 50, size=(5, 3))

# Step 2: Convert the array into a DataFrame
df_data = pd.DataFrame(data, columns=['X', 'Y', 'Z'])
print("Generated Data:\n", df_data)

# Step 3: Apply NumPy functions to DataFrame columns
df_data['Log_X'] = np.log(df_data['X'])
df_data['Sqrt_Y'] = np.sqrt(df_data['Y'])
print("DataFrame with NumPy Transformations:\n", df_data)

# Step 4: Analyze data using Pandas correlation
print("Correlation Matrix:\n", df_data.corr())

Generated Data:
     X   Y   Z
0  27  21  31
1  17  36  28
2  10  19  17
3   1  19   3
4  47  36   4
DataFrame with NumPy Transformations:
     X   Y   Z     Log_X    Sqrt_Y
0  27  21  31  3.295837  4.582576
1  17  36  28  2.833213  6.000000
2  10  19  17  2.302585  4.358899
3   1  19   3  0.000000  4.358899
4  47  36   4  3.850148  6.000000
Correlation Matrix:
                X         Y         Z     Log_X    Sqrt_Y
X       1.000000  0.642391 -0.020830  0.862392  0.648930
Y       0.642391  1.000000  0.017913  0.594696  0.999887
Z      -0.020830  0.017913  1.000000  0.414375  0.027788
Log_X   0.862392  0.594696  0.414375  1.000000  0.602687
Sqrt_Y  0.648930  0.999887  0.027788  0.602687  1.000000


In [21]:
# --- Try It: NumPy + Pandas Integration ---

# 1. Compute overall column statistics using np.mean() and np.median()
# You can apply NumPy functions directly to Pandas columns (Series)
mean_stats = np.mean(df_data[['X', 'Y', 'Z']], axis=0)
median_stats = np.median(df_data[['X', 'Y', 'Z']], axis=0)

print("Column Means (X, Y, Z):\n", mean_stats)
print("\nColumn Medians (X, Y, Z):\n", median_stats)

# 2. Apply np.square() and np.exp()
# We'll create new columns for these results
df_data['Square_Z'] = np.square(df_data['Z'])
df_data['Exp_X_Small'] = np.exp(df_data['X'] / 10)  # Scaling X down so exp doesn't get too huge

print("\nDataFrame with Square and Exp Transformations:\n", df_data)

Column Means (X, Y, Z):
 X    20.4
Y    26.2
Z    16.6
dtype: float64

Column Medians (X, Y, Z):
 [17. 21. 17.]

DataFrame with Square and Exp Transformations:
     X   Y   Z     Log_X    Sqrt_Y  Square_Z  Exp_X_Small
0  27  21  31  3.295837  4.582576       961    14.879732
1  17  36  28  2.833213  6.000000       784     5.473947
2  10  19  17  2.302585  4.358899       289     2.718282
3   1  19   3  0.000000  4.358899         9     1.105171
4  47  36   4  3.850148  6.000000        16   109.947172


# Importing and Summarizing Data Using Pandas

In [24]:
# Step 1: Save the DataFrame to a CSV file
df_data.to_csv('sample_data.csv', index=False)
print("Data saved to 'sample_data.csv'.")

# Step 2: Load the CSV file back into a new DataFrame
df_imported = pd.read_csv('sample_data.csv')
print("Imported DataFrame:\n", df_imported)

# Step 3: Generate summary statistics
summary_stats = df_imported.describe()
print("Summary Statistics:\n", summary_stats)

# Step 4: Display column means and standard deviations
print("Column Means:\n", df_imported.mean())
print("Column Standard Deviations:\n", df_imported.std())

Data saved to 'sample_data.csv'.
Imported DataFrame:
     X   Y   Z     Log_X    Sqrt_Y  Square_Z  Exp_X_Small
0  27  21  31  3.295837  4.582576       961    14.879732
1  17  36  28  2.833213  6.000000       784     5.473947
2  10  19  17  2.302585  4.358899       289     2.718282
3   1  19   3  0.000000  4.358899         9     1.105171
4  47  36   4  3.850148  6.000000        16   109.947172
Summary Statistics:
                X          Y          Z     Log_X    Sqrt_Y    Square_Z  \
count   5.000000   5.000000   5.000000  5.000000  5.000000    5.000000   
mean   20.400000  26.200000  16.600000  2.456357  5.060075  411.800000   
std    17.657859   8.983318  13.049904  1.487173  0.862876  439.925789   
min     1.000000  19.000000   3.000000  0.000000  4.358899    9.000000   
25%    10.000000  19.000000   4.000000  2.302585  4.358899   16.000000   
50%    17.000000  21.000000  17.000000  2.833213  4.582576  289.000000   
75%    27.000000  36.000000  28.000000  3.295837  6.000000  784.0

In [28]:
# --- Try It: Add calculated column and save ---

# 1. Add a new calculated column 'Sum_XY'
# This assumes your CSV has columns named 'X' and 'Y'
df_imported['Sum_XY'] = df_imported['X'] + df_imported['Y']

# 2. Save the modified DataFrame to a new CSV file
df_imported.to_csv('modified_sample_data.csv', index=False)

# Review the changes
print("\nModified DataFrame with Sum_XY:\n", df_imported.head())
print("\nModified data saved to 'modified_sample_data.csv'.")


Modified DataFrame with Sum_XY:
     X   Y   Z     Log_X    Sqrt_Y  Square_Z  Exp_X_Small  Sum_XY
0  27  21  31  3.295837  4.582576       961    14.879732      48
1  17  36  28  2.833213  6.000000       784     5.473947      53
2  10  19  17  2.302585  4.358899       289     2.718282      29
3   1  19   3  0.000000  4.358899         9     1.105171      20
4  47  36   4  3.850148  6.000000        16   109.947172      83

Modified data saved to 'modified_sample_data.csv'.


# Data Grouping and Aggregation

In [29]:
import pandas as pd
import numpy as np

# Step 1: Load the dataset
df_kaggle = pd.read_csv('survey_results_public.csv')
print("Loaded Dataset head:\n", df_kaggle.head())

# Step 2: Select relevant columns (UPDATED NAMES)
# Changed 'ConvertedComp' to 'ConvertedCompYearly' for the 2023 dataset
df_subset = df_kaggle[['Country', 'EdLevel', 'YearsCodePro', 'ConvertedCompYearly']]

# Step 3: Clean data by dropping missing values
df_clean = df_subset.dropna().copy()

# Step 4: Categorize experience (Data cleaning included)
# YearsCodePro often contains strings like "More than 50 years", so we convert to numbers
df_clean['YearsCodePro'] = pd.to_numeric(df_clean['YearsCodePro'], errors='coerce')
df_clean = df_clean.dropna() # Drop rows that couldn't be turned into numbers

df_clean['ExperienceLevel'] = np.where(df_clean['YearsCodePro'] >= 10, 'Senior', 'Junior')

# Step 5: Group by Country and ExperienceLevel
grouped_data = df_clean.groupby(['Country', 'ExperienceLevel'])['ConvertedCompYearly'].mean()

# Step 6: Reset index for readability
grouped_data = grouped_data.reset_index()
print("\nFinal Grouped Data:\n", grouped_data.head(10))

Loaded Dataset head:
    ResponseId     Q120                      MainBranch              Age  \
0           1  I agree                   None of these  18-24 years old   
1           2  I agree  I am a developer by profession  25-34 years old   
2           3  I agree  I am a developer by profession  45-54 years old   
3           4  I agree  I am a developer by profession  25-34 years old   
4           5  I agree  I am a developer by profession  25-34 years old   

                                          Employment  \
0                                                NaN   
1                                Employed, full-time   
2                                Employed, full-time   
3                                Employed, full-time   
4  Employed, full-time;Independent contractor, fr...   

                             RemoteWork  \
0                                   NaN   
1                                Remote   
2  Hybrid (some remote, some in-person)   
3  Hybrid (some re

In [36]:
# --- Try It: Final Analysis Tasks ---

# 1. Change the grouping to EdLevel and compute Median/Std
# This helps see how salary correlates with education
ed_stats = df_clean.groupby('EdLevel')['ConvertedCompYearly'].agg(['median', 'std'])
print("Salary Statistics by Education Level:\n", ed_stats)

# 2. Explore top 10 countries with the highest average compensation
# We group by Country, find the mean, and sort descending
country_ranking = df_clean.groupby('Country')['ConvertedCompYearly'].mean().sort_values(ascending=False)

print("\nTop 10 Countries by Average Compensation:\n", country_ranking.head(10))

Salary Statistics by Education Level:
                                                      median           std
EdLevel                                                                  
Associate degree (A.A., A.S., etc.)                 74351.0  1.064956e+05
Bachelor’s degree (B.A., B.S., B.Eng., etc.)        80317.0  5.250941e+05
Master’s degree (M.A., M.S., M.Eng., MBA, etc.)     74963.0  1.349528e+05
Primary/elementary school                           60390.0  3.973693e+06
Professional degree (JD, MD, Ph.D, Ed.D, etc.)      81388.0  1.738702e+06
Secondary school (e.g. American high school, Ge...  58899.0  3.945440e+05
Some college/university study without earning a...  71683.0  1.222443e+05
Something else                                      59481.0  7.640611e+04

Top 10 Countries by Average Compensation:
 Country
Mali                        9.156200e+06
Afghanistan                 9.279349e+05
Ethiopia                    7.220749e+05
Thailand                    6.340456e+05
Nomad